version: "3"

services:
  sitemap-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_DATA: ./build
    env_file:
      - .env
    ports:
      - 8080:8080

volumes:
  postgres:
